export const certificates = [
  {
    id: 1,
    issuer: 'British Airways',
    issuerColor: '#1f4e8c',
    title: 'Data Science Job Simulation',
    date: 'Issued on: Jun 27, 2026',
    credId: 'heAettzhN83F5jm9B',
    type: 'Job Simulation Programme (Forage)',
    file: 'british-airways.jpg',
  },
  {
    id: 2,
    issuer: 'Tata Group',
    issuerColor: '#003c71',
    title: 'GenAI Powered Data Analytics Job Simulation',
    date: 'Issued on: Jun 27, 2026',
    credId: 'GDS7B3LM6HT64P2F2',
    type: 'Job Simulation Programme (Forage)',
    file: 'tata-genai.jpg',
  },
  {
    id: 3,
    issuer: 'Deloitte',
    issuerColor: '#86bc25',
    title: 'Data Analytics Job Simulation',
    date: 'Issued on: Jun 27, 2026',
    credId: 'u6h4rY24c5zJnPQve',
    type: 'Job Simulation Programme (Forage)',
    file: 'deloitte.jpg',
  },
  {
    id: 4,
    issuer: 'AICTE x Edunet x Shell',
    issuerColor: '#0a3d91',
    title: 'AI & Data Analytics Virtual Internship (Skills4Future)',
    date: 'Jul 15 – Aug 16, 2025',
    credId: 'STU686293940e3771751290772',
    type: 'Internship Certificate',
    file: 'aicte-edunet.jpg',
  },
  {
    id: 5,
    issuer: 'Elevate Labs',
    issuerColor: '#6a3de8',
    title: 'AI & Machine Learning Internship — Best Performer',
    date: 'Aug 4 – Sep 20, 2025',
    credId: 'Skill India / MSME',
    type: 'Internship Certificate',
    file: 'elevate-labs.jpg',
  },
  {
    id: 6,
    issuer: 'LinkedIn Learning',
    issuerColor: '#0a66c2',
    title: 'SQL Essential Training',
    date: 'Issued on: Jul 1, 2025',
    credId: '205aef781a384e2742aa2d323f94a893a17af827b7a62703a9292745496719a1',
    type: 'CPE-Accredited Course Certificate',
    file: 'linkedin-sql.jpg',
  },
  {
    id: 7,
    issuer: 'UniAthena x Acacia University',
    issuerColor: '#d6336c',
    title: 'Essentials of Data Visualization using MS Excel',
    date: 'Issued on: May 11, 2025',
    credId: '8251-4881-3678',
    type: 'Professional Development Certificate',
    file: 'uniathena-excel.jpg',
  },
  {
    id: 8,
    issuer: 'CognitiveClass.ai (IBM)',
    issuerColor: '#1f6feb',
    title: 'Python 101 for Data Science',
    date: 'Issued on: May 11, 2025',
    credId: '7c55b2c64f54423392695254f39462ee',
    type: 'Course Certificate',
    file: 'cognitiveclass-python.jpg',
  },
  {
    id: 9,
    issuer: 'IJIRT',
    issuerColor: '#1f4e8c',
    title: 'A Cognitive-Aware AI Framework for Personalized Learning Support',
    date: 'Registration ID: 200232',
    credId: 'ISSN 2349-6002',
    type: 'Certificate of Publication',
    file: 'ijirt-publication.jpg',
  },
]

// Drop a matching image into public/images/certificates/ (filenames above)
// and it will automatically replace the placeholder preview.
export function getCertificateImage(cert) {
  return `${import.meta.env.BASE_URL}images/certificates/${cert.file}`
}
